name: SimpleChatChannels
main: me.odium.simplechatchannels.Loader
version: 0.1
description: Simple Chat Channels
commands:
   scc:
      description: fucksme
      permission:
      usage: /omenu
   addchan:
      description: fucksme
      permission:
      usage: /ocreate <channelname>
   delchan:
      description: fucksme
      permission:
      usage: /odelete <channelname>
   adduser:
      description: fucksme
      permission:
      usage: /oadd <channelname> <playername>
   deluser:
      description: fucksme
      permission:
      usage: /oremove <channelname> <playername>
   addowner:
      description: fucksme
      permission:
      usage: /oadd <channelname> <playername>
   delowner:
      description: fucksme
      permission:
      usage: /oremove <channelname> <playername>
   chanlist:
      description: fucksme
      permission:
      usage: /olist [channelname] [owner]
   schat:
      description: fucksme
      permission:
      usage: /schat <channelname> [message]