CyniChat:
  channels:
    default: "Global"
  database:
    host: "localhost"
    port: 3306
    username: "root"
    password: "pass"
    database: "cynichat"
    prefix: "chat_"
  bungee:
    name: "lobby"
  other:
    data: "json"
    debug: "true"
    bungee: "true"
