CyniChat:
  channels:
    default: "Global"
  database:
    host: "localhost"
    port: 3306
    username: "root"
    password: "pass"
    database: "cynichat"
    prefix: "chat_"
  other:
    data: "json"
    debug: "true"
    irc: "false"
    bungee: "true"
  irc:
    hostname: "127.0.0.1"
    port: 6667
    nickname: "CyniBot"
  bungee:
    connected: 
    - minecraft
    - craftmine