CyniChat:
  channels:
    default: "Global"
  database:
    host: "localhost"
    port: "3306"
    username: "root"
    password: "pass"
    database: "cynichat"
    prefix: "chat_"
  other:
    data: "json"
    debug: "false"
    irc: "true"
  irc:
    hostname: "127.0.0.1"
    port: 54127
    nickname: "CyniBot"
    channel: "#m4test"
