name: CyniChat
version: 0.0.1
description: A new chat system for Minecraft
load: STARTUP
author: Cynical
main: uk.co.CyniCode.CyniChat.CyniChat
commands:
  ch:
    description: This is a large.
    usage: /ch help
  r:
    description: Replies to a person.
    usage: /r <message>
  me:
    description: Sends a message in the context of the user.
    usage: /me <action>
  afk:
    description: Sets you as afk.
    usage: /afk
  msg:
    description: Sends a message to someone.
    usage: /msg <player> <message>
permissions:
  cynichat.*:
    description: Gives access to all CyniChat commands
    children:
      cynichat.basic.*: true
      cynichat.mod.*: true
      cynichat.admin.*: true
    default: op
  cynichat.basic.*:
    description: Gives basic access to CyniChat
    children:
      cynichat.basic.chat: true
      cynichat.basic.join: true
      cynichat.basic.leave: true
    default: true
  cynichat.basic.chat:
    description: Allows a player to chat
    default: true
  cynichat.basic.join:
    description: Allows a player to switch channels
    default: true
  cynichat.basic.leave:
    description: Allows a player to leave the channel
    default: true
  cynichat.mod.*:
    description: Allows for all mod actions to be carried out
    children:
      cynichat.mod.kick: true
      cynichat.mod.ban: true
      cynichat.mod.mute: true
    default: op
  cynichat.mod.kick:
    description: Allows for players to be kicked from channels
    default: false
  cynichat.mod.ban:
    description: Allows for players to be banned from channels
    default: false
  cynichat.mod.mute:
    description: Allows for players to be muted from channels
    default: false
  cynichat.admin.*:
    description: Allows for all admin actions to be carried out
    children:
      cynichat.admin.silence: true
      cynichat.admin.create: true
      cynichat.admin.remove: true
    default: op
  cynichat.admin.silence:
    description: Allows for players to be silenced on the server
    default: false
  cynichat.admin.create:
    description: Allows for channels to be created
    default: false
  cynichat.admin.remove:
    description: Allows for channels to be removed
    default: false